language: android
sudo: required
jdk: oraclejdk8

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

env:
  global:
  - ANDROID_API=26
  - EMULATOR_API=21
  - ANDROID_BUILD_TOOLS=27.0.3
  - ADB_INSTALL_TIMEOUT=5
  - KEYSTORE_NAME=.keystore
  - KEY_ALIAS=key0
  - secure: ijtn6B8w1hccDD7rEBK2WAL9yuyjjb+zmgI48kSj3vi63d5tgucBJm12FjB5amN/53j3w73OovyT7TrUFteM8XxrAPdVY6AjEz0L/qdrAbUzMX6taotNgHTHNdl5dHOMQxt4nOBYPVHlPPWk7bHInBWoD0Ph4JXnmL/l6d7M740D29AomMeBOowloH5WmDsZnCtPrViUQlt4rprSeXyoY7KJlkDc4ngqtQlY04h6l5wHwjkr+JdNk2lVGTBgSU/nvKjImsWR2QQg2afZgB0aAev+ZuE5+Y3sc0MVeL+piukCg7PdEt5EvCe7o8SMBLN8PuuxT0+ZAG1t1lRP/hm5nX8x29s/afzpM4a2HsR33arxckGseqpTmPv+MGdmD+CTsxDjmlRQQ+TyjDGmp+vFBKNUmG1sz9jJuPQyAFNfjOaPzzDzee4D1JTYXzANnnwn2ygJg7zX8OR8widA2j9orufz9abNdhof8KXnRBLCVd7wreSQv8eeAoJVMesNjzZ6BTpPRHmh+guTb0pguUH7eyy/nBrmBoWgkrMjdb+o7XQ8ItA4Uj+QOZnm2LQG7SsWbS4i5DOs7xq0iWBgprLdRxkt8qOhWswidxy1HUf3GvwoNekkkJz0fVUMZODHGDEZu0KaTZepmv5L7agDsFXubOyAqQH4G3X8G2AGLVhugcs=
  - secure: ZeJVMD5mmRuOjOT16epMcVq8ukLWz38Ijz6l7BhIsMUYOk5LPsRxASBfIJktAbwwh2R7cfi8YxgOP69gjyDgzaVSdAe0SKYZXC2BTA0t+V0t91DWN6zwM+cT9H49IqUrHGzAdo9tcb9doTzvJM9edkO/nM+5fhnti3TEHsY/5KUxn2CvclnQxxR5JvIVljKH+8WZ5sl6GAK6eMJYg7RS0GhRI0AI8bnkejqli6p2sPhjLzyRPKp//oZdaqzIFVzSet0cmByhHE2PQGBwECu933hbMz7mms02KFT5RdNxnz3SaGhvo9xym0QQfuZtZo2hCnuzPxbOJwRUgW4rpR4GYgAWuqeNRXy+FCBuirW5GQpkwxKxZjvlRejdfZNTdD+bluZP9zKzX6r15sSkGJ7cTaf2NATA+tGWxEGf4UgmPd13c79DgiNRGHE8oYoQ55MEGllB0cv3PkyPLbOXnK8heIyQYHlExkvki0vfV2up8Km4OiV0kFzYev4uqOy8278vIPaefSfTqKbasycdaIhwrr2IOSaS7IjATTjyqbljtESV+TWzYHRVQ356LaGkr78126vf2M0wRoqkoQO3CFlL7ZzGUELbS8IOcVICeNB41GQrDogSxlW7NS/0sIslgbPjhLX+KdYuzm/aZFq0tZcrTViK/a8VhGSruqkMHm2xpsA=

android:
  components:
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - platform-tools
  - tools
  - android-$ANDROID_API
  - android-$EMULATOR_API
  - extra-google-google_play_services
  - extra-google-m2repository
  - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API
  - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API
  licenses:
  - android-sdk-preview-license
  - android-sdk-license
  - google-gdk-license-.+
  - intel-android-extra-license

before_install:
- openssl aes-256-cbc -K $encrypted_0b856137f4eb_key -iv $encrypted_0b856137f4eb_iv -in $KEYSTORE_NAME.enc -out $KEYSTORE_NAME -d
- mkdir "$ANDROID_HOME/licenses" || true
- cp android-sdk-license $ANDROID_HOME/licenses
- chmod +x gradlew
- ./gradlew dependencies || true

script:
- ./gradlew clean build -PdisablePreDex --stacktrace

before_deploy:
- cp $TRAVIS_BUILD_DIR/$KEYSTORE_NAME $HOME
- cd app/build/outputs/apk/release
- INTERMEDIATE_FILENAME="$(ls *-release-unsigned.apk)"
- APK_FILENAME=familyhub-$TRAVIS_TAG-build$TRAVIS_BUILD_NUMBER.apk
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/$KEYSTORE_NAME -storepass $storepass -keypass $keypass $INTERMEDIATE_FILENAME $KEY_ALIAS
- jarsigner -verify $INTERMEDIATE_FILENAME
- ls ${ANDROID_HOME}/build-tools/
- ${ANDROID_HOME}/build-tools/$ANDROID_BUILD_TOOLS/zipalign -v 4 $INTERMEDIATE_FILENAME $APK_FILENAME

deploy:
  provider: releases
  file: $APK_FILENAME
  skip_cleanup: true
  on:
    repo: benleavett/familyhub
    tags: true
    jdk: oraclejdk8
  api_key:
    secure: YbT5tlduKekcVcAHqgfnNLI945NChGoiNbmWlFf3wUTFQs93Z/Ylv6/xsVvzTcaRWtxV2RquSQPcOzOj4ejM0jxX/J61rKcT3gVA4rYJ1Gjd/q0XqfakZf0vH7GUpdjtS0Es6QW0yGZvHnmNoYxSHuoI6GPuUkwe94n/CbPLKF2AIgkTPyO672DqtBg21qa3sQ7IzAwZHkIoaJLC+RnfaA1UDzUqwlQFeugJ2NmvWE38tPMq4ig/eE1sNHJrDTmK79jXPHpr3E5LcbSluWfrFR++GdPGwyUVoiA82zxNWHCNU6XV4T5rlHstejrLucpo5gujd9JUNBce+t9hul1I/83xogGCTJImCHZdErUwTzfuKPVWgYr0vEXsmv8A4x+H8iXX1+Bxi0V1rP92Nlj7dyJ+y89DgLDUMOkS9cFzjCzRQo1wbjWB1tc6DEdDtw8hcZumBany6wLWCjayOAajPpMj42F2hTqLgHhdzlJtpTVWnxQemdom3xlV6nTixl1gRU8DPOhn1e1vKqZx1WvBniAi1KXbH1JpX3NoSaXFgPAtKwcuISX1iTO90R7nFgJh4MdlIn64WlOFxyFG9fvFSboGAz7ZJhgrWVxy3nB4cAFfSw58tQJW6mWihpVhoqTuinpaPwT9vcaha233sAw6WmJEFTlgufPCVMO3ngicHBo=
